# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestListofjobvacancies():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_listofjobvacancies(self):
    self.driver.get("https://tr.indeed.com/")
    self.driver.set_window_size(800, 818)
    WebDriverWait(self.driver, 30).until(expected_conditions.visibility_of_element_located((By.XPATH, "//input[@id=\'text-input-what\']")))
    self.driver.find_element(By.ID, "text-input-what").send_keys("yazılım mühendisi")
    WebDriverWait(self.driver, 30).until(expected_conditions.visibility_of_element_located((By.XPATH, "//form[@id=\'jobsearch\']/div/div/div[3]/div/div/span/input")))
    self.driver.find_element(By.ID, "text-input-where").send_keys("istanbul")
    WebDriverWait(self.driver, 30).until(expected_conditions.visibility_of_element_located((By.XPATH, "//button[@type=\'submit\']")))
    self.driver.find_element(By.CSS_SELECTOR, ".yosegi-InlineWhatWhere-primaryButton").click()
    self.driver.close()
  
